import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import { ApolloWrapper } from "./graphql/apollo-wrapper";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {children: React.ReactNode }) {
  return (
    <ApolloWrapper>
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </ApolloWrapper>
  )
}
